app_name                = ""
availability_zones      = []
backup_retention_period = 1
db_port                 =
engine_type             = ""
engine_version          = ""
engine_mode             = ""
instance_class          = ""
instances_amount        = 0
master_db_user          = ""
encrypted               = true
scaling_configuration   = {}
bation_sg_id            = ""
